### ISSUE TITLE
Log new insert state

### ISSUE THREAD

**Issue by LensHunnel** [dotpy/py-pf#15]
Hello,

I'm trying to log new insert state. My approach was to parse pfsync packets with scapy and extract new state and log it.  It seems like py-pf can get states and parse it right ? It is possible to use py-pf for this use case ? 

Thanks your work.

Lens

**Comment by dotpy** [comment]
Hi @LensHunnel ,
Yes, py-pf can read Packet Filter's state table, and (if needed) clear/kill states.
However the approach would be very different: with scapy you'd see state packets "live", as they travel over the network, while with py-pf you would retrieve the full state-table from the kernel.
I think you could loop over PFState objects returned by `PacketFilter.get_states()` and look for PFState objects that have a recent `creation` time.
I hope this is not too messy... :-D
Cheers,
Daniele

**Comment by LensHunnel** [comment]
Hi @dotpy ,

Thanks for your answer.
py-pf only works on openbsd? I tried on freebsd 12 and it returns :
```
>>> import pf
>>> p = pf.PacketFilter()
>>> p.get_status()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "build/bdist.freebsd-11.2-RELEASE-p9-amd64/egg/pf/filter.py", line 346, in get_status
IOError: [Errno 19] Operation not supported by device
```

It seems like py-pf and pfsync are using the same structure for state perhaps I can use py-pf's Structure to extract info from raw data(state packets "live")?

**Comment by dotpy** [comment]
Hi @LensHunnel ,

Sorry for the late reply, I was on vacation... :-D
Yes, py-pf only works on OpenBSD; I ported it once to FreeBSD, but, since PF versions always differ between OpenBSD and FreeBSD, it was too time-consuming for me to maintain both versions.
I have no idea of what a pfsync packet looks like, but yes, if it uses the same structure, you can definitely try to parse it into a `pfsync_state` structure.
